export const ADD_FLOOR_TO_ELEVATOR_QUE = "ADD_FLOOR_TO_ELEVATOR_QUE";

export const PASS_FLOOR_TO_ELEVATOR = "PASS_FLOOR_TO_ELEVATOR";

export const CHANGE_ELEVATOR_CURRENT_FLOOR = "CHANGE_ELEVATOR_CURRENT_FLOOR";

export const CHANGE_ELEVATOR_BUSY_STATUS = "CHANGE_ELEVATOR_BUSY_STATUS";

export const GET_STATE_FROM_STORAGE = "GET_STATE_FROM_STORAGE";